[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vlsy"
version = "3.0.3"
description = "Vlsy - Un formato de archivo todo en uno"
readme = "README.md"
authors = [{name = "Lucas Sogaray"}]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Filesystems",
]

dependencies = [
    "cryptography",
    "pillow"
]


[project.urls]
"Source Code" = "https://github.com/lucassogarayDA/hbf"
"Documentation" = "https://github.com/lucassogarayDA/hbf#readme"
"Issue Tracker" = "https://github.com/lucassogarayDA/hbf/issues"


[project.scripts]
vlsy = "vlsy:main"

[tool.setuptools]
py-modules = ["vlsy"]
